version: "3.7"

volumes:
  provider: {}
  yagna: {}

services:
  node:
    # Using a specific name allows there to be one instance per compose project.
    container_name: ${COMPOSE_PROJECT_NAME}
    image: whalen/golem-node-fedora
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - provider:/root/.local/share/ya-provider/
      - yagna:/root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - YA_PAYMENT_NETWORK=${YA_PAYMENT_NETWORK}
      - YA_ACCOUNT=${YA_ACCOUNT}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.golem-clean.schedule: "@daily"
      ofelia.job-exec.golem-clean.command: "find /root/.local/share/ya-provider/exe-unit/cache/ -mtime +7 -type f -exec rm {} +"
