version: "3.7"

volumes:
  provider: {}
  yagna: {}

services:
  node:
    # Using a specific name allows there to be one instance per compose project.
    container_name: ${COMPOSE_PROJECT_NAME}
    image: whalen/golem-node-fedora
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        FEDORA_BASE: registry.fedoraproject.org/fedora
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - provider:/root/.local/share/ya-provider/
      - yagna:/root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - YA_PAYMENT_NETWORK=${YA_PAYMENT_NETWORK}
      - YA_ACCOUNT=${YA_ACCOUNT}
    labels:
      ofelia.enabled: "true"
      # Use different hour for different services. Example: 3 AM.
      ofelia.job-exec.golem-clean.schedule: "0 0 3 * * 0" # Once per week on Sunday.
      ofelia.job-exec.golem-clean.command: "find /root/.local/share/ya-provider/exe-unit/cache/ -mtime +7 -type f -exec rm {} +"

  scheduler:
    image: mcuadros/ofelia
    command: daemon --docker
    depends_on:
      - node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

